# Generated by Django 5.1 on 2024-08-19 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('numero', models.CharField(max_length=50)),
                ('sexe', models.IntegerField(choices=[(1, 'Masculin'), (2, 'Féminin')])),
                ('age', models.IntegerField()),
                ('statut_matrimonial', models.IntegerField(choices=[(1, 'Célibataire'), (2, 'Mariée'), (3, 'Divorcée'), (4, 'Veuve'), (5, 'Union libre')])),
                ('niveau_etude', models.IntegerField(choices=[(1, 'Aucun'), (2, 'Primaire'), (3, 'Secondaire'), (4, 'Supérieur')])),
                ('activite_parallele', models.IntegerField(choices=[(1, 'Non'), (2, 'Oui')])),
                ('revenu_mensuel', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnie', models.IntegerField(choices=[(1, 'Bantous'), (2, 'Semi-bantous'), (3, 'Soudanais')])),
                ('religion', models.IntegerField(choices=[(1, 'Chrétienne'), (2, 'Musulmane'), (3, 'Animiste'), (4, 'Autres')])),
                ('residence', models.IntegerField(choices=[(1, 'Urbaine'), (2, 'Rurale')])),
                ('mise_hors_service', models.IntegerField(choices=[(1, 'Médicale'), (2, 'Volontaire'), (3, 'Limite d’âge'), (4, 'Involontaire')])),
                ('grade_actuel', models.IntegerField(choices=[(1, 'Soldat'), (2, 'Militaire de rang'), (3, 'Sous-officier'), (4, 'Officier subalterne'), (5, 'Officier supérieur')])),
                ('annees_service', models.IntegerField()),
                ('corps_armee', models.IntegerField(choices=[(1, 'Armée de terre'), (2, 'Armée de l’Air'), (3, 'Gendarmerie Nationale'), (4, 'Marine nationale'), (5, 'Garde Présidentielle'), (6, 'BIR')])),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.IntegerField(choices=[(1, 'Moins de 18,5'), (2, '18,5-24,99'), (3, '25-29,99'), (4, '30-34,99'), (5, '35-39,99'), (6, '40 et plus')])),
                ('pression_arterielle', models.IntegerField(choices=[(1, '<139/89'), (2, '140/90-159/99'), (3, '160/100-179/109'), (4, '>=180/110')])),
                ('glycemie', models.IntegerField(choices=[(1, '- de 0,60'), (2, '0,70-1,10'), (3, '1,10-1,26'), (4, '+ de 1,26')])),
                ('test_vih', models.IntegerField(choices=[(1, 'Négatif'), (2, 'Positif')])),
            ],
        ),
    ]
