# Generated by Django 5.1 on 2024-08-21 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('numero', models.CharField(max_length=50)),
                ('sexe', models.IntegerField(choices=[(1, 'Masculin'), (2, 'Féminin')])),
                ('age', models.IntegerField(choices=[(1, '55-60 ans'), (2, '60-65 ans'), (3, '65-70 ans'), (4, '70-75 ans'), (5, '+75 ans')])),
                ('statut_matrimonial', models.IntegerField(choices=[(1, 'Célibataire'), (2, 'Mariée'), (3, 'Divorcée'), (4, 'Veuve'), (5, 'Union libre')])),
                ('niveau_etude', models.IntegerField(choices=[(1, 'Aucun'), (2, 'Primaire'), (3, 'Secondaire'), (4, 'Supérieur')])),
                ('activite_parallele', models.IntegerField(choices=[(1, 'Non'), (2, 'Oui')])),
                ('revenu_mensuel', models.IntegerField(blank=True, choices=[(1, 'SMIC'), (2, '2SMIC'), (3, '3SMIC'), (4, '4SMIC'), (5, '+4SMIC')], null=True)),
                ('ethnie', models.IntegerField(choices=[(1, 'Bantous'), (2, 'Semi-bantous'), (3, 'Soudanais')])),
                ('religion', models.IntegerField(choices=[(1, 'Chrétienne'), (2, 'Musulmane'), (3, 'Animiste'), (4, 'Autres')])),
                ('residence', models.IntegerField(choices=[(1, 'Urbaine'), (2, 'Rurale')])),
                ('mise_hors_service', models.IntegerField(choices=[(1, 'Médicale'), (2, 'Volontaire'), (3, 'Limite d’âge'), (4, 'Involontaire')])),
                ('grade_actuel', models.IntegerField(choices=[(1, 'Soldat'), (2, 'Militaire de rang'), (3, 'Sous-officier'), (4, 'Officier subalterne'), (5, 'Officier supérieur')])),
                ('annees_service', models.IntegerField(choices=[(1, '<5 ans'), (2, '5-15 ans'), (3, '15-35 ans'), (4, '>35 ans')])),
                ('corps_armee', models.IntegerField(choices=[(1, 'Armée de terre'), (2, 'Armée de l’Air'), (3, 'Gendarmerie Nationale'), (4, 'Marine nationale'), (5, 'Garde Présidentielle'), (6, 'BIR')])),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.IntegerField(choices=[(1, 'Moins de 18,5'), (2, '18,5-24,99'), (3, '25-29,99'), (4, '30-34,99'), (5, '35-39,99'), (6, '40 et plus')])),
                ('pression_arterielle', models.IntegerField(choices=[(1, '<139/89'), (2, '140/90-159/99'), (3, '160/100-179/109'), (4, '>=180/110')])),
                ('glycemie', models.IntegerField(choices=[(1, '- de 0,60'), (2, '0,70-1,10'), (3, '1,10-1,26'), (4, '+ de 1,26')])),
                ('test_vih', models.IntegerField(choices=[(1, 'Négatif'), (2, 'Positif')])),
                ('cognition_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Avez-vous des problèmes de mémoire ou d’orientation ?')),
                ('cognition_2', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Avez-vous constaté une aggravation de ces problèmes ?')),
                ('cognition_3', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Quelle est la date complète d’aujourd’hui ?')),
                ('nutrition_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Perte de poids involontaire')),
                ('nutrition_2', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="Perte d'appétit")),
                ('vision_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="Problèmes de vue ou maladies de l'œil")),
                ('vision_2', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Consultation ophtalmologue')),
                ('vision_3', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Baisse de vue')),
                ('audition_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Audition oreille droite')),
                ('audition_2', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Audition oreille gauche')),
                ('audition_3', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="Baisse d'audition")),
                ('santePsychique_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Sentiment de déprime')),
                ('santePsychique_2', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="Manque d'intérêt")),
                ('mobilite_1', models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Levers de chaise 14s')),
            ],
        ),
    ]
