# Generated by Django 5.1 on 2024-08-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icope', '0005_alter_questionnaire_cognition_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='cognition_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='Avez-vous des problèmes de mémoire ou d’orientation ?'),
        ),
    ]
