# Generated by Django 5.1 on 2024-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icope', '0007_questionnaire_audition_questionnaire_cognition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='numero',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='statut',
            field=models.IntegerField(choices=[(1, 'Veterant'), (2, 'Autre')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='test_hepatite',
            field=models.IntegerField(choices=[(1, 'Négatif'), (2, 'Positif')], default=0),
            preserve_default=False,
        ),
    ]
