# Generated by Django 5.1 on 2024-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icope', '0010_alter_questionnaire_audition_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='audiometrie_score',
            field=models.IntegerField(blank=True, choices=[(0, 'Audition normale (<35 dB)'), (1, 'Perte modérée-sévère (35-80 dB)'), (2, 'Surdité (>81 dB)')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='conditions_nutrition',
            field=models.IntegerField(blank=True, choices=[(0, 'Nécessite une assistance'), (1, 'Se nourrit seul avec difficulté'), (2, 'Se nourrit seul sans difficulté')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='gpcog_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='maladie_aigue_3_mois',
            field=models.IntegerField(blank=True, choices=[(1, 'OUI'), (0, 'NON')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mna_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='phq9_score',
            field=models.IntegerField(blank=True, choices=[(0, 'Pas de trouble de l’humeur'), (1, '1-2 symptômes, A risque'), (2, 'Dépression, >3 symptômes')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='q401',
            field=models.IntegerField(blank=True, choices=[(1, 'Correct'), (0, 'Incorrect')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='q409',
            field=models.IntegerField(blank=True, choices=[(0, 'Jamais'), (1, 'Plusieurs jours'), (2, 'Plus de la moitié du temps'), (3, 'Presque tous les jours')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='q410',
            field=models.IntegerField(blank=True, choices=[(0, 'Durée'), (1, 'Qualité'), (2, 'Régularité')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='q411',
            field=models.IntegerField(blank=True, choices=[(0, 'Jamais'), (1, 'Plusieurs jours'), (2, 'Plus de la moitié du temps'), (3, 'Presque tous les jours')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='q413',
            field=models.IntegerField(blank=True, choices=[(0, 'Non réalisable'), (1, '>16.70s'), (2, '13.70-16.69s'), (3, '11.20-13.69s'), (4, '≤11.19s')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='score_depistage_nutritionnel',
            field=models.IntegerField(blank=True, choices=[(0, '12-14 points'), (1, '8-11 points'), (2, '0-7 points')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='snellen_score',
            field=models.IntegerField(blank=True, choices=[(1, 'Pas de déficience visuelle'), (2, 'Déficience visuelle')], null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sppb_score',
            field=models.IntegerField(blank=True, choices=[(1, 'SPPB Score 10-12 : Mobilité normale'), (2, 'SPPB Score 7-9 : Perte modérée de la mobilité'), (3, 'SPPB Score 0-6 : Altération sévère de la mobilité')], null=True),
        ),
    ]
