# Generated by Django 5.1 on 2024-08-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icope', '0013_alter_questionnaire_a_audiometrie_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='audition_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="AUDITION - Se mettre derrière le sujet (à distance d’un bras ou à environ 0,6 m) pour qu’il ne puisse pas lire sur les lèvres. Demander-lui de placer un doigt sur le tragus de l'oreille gauche pour obscurcir le son. Chuchoter (maison, matin), La personne a-t-elle pu répéter tous les mots Pour l’oreille droite :"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='audition_2',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='AUDITION - Pour l’oreille gauche :'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='audition_3',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='AUDITION - Est-ce que vous ou votre entourage avez l’impression que votre audition a baissé au cours des 6 derniers mois ou depuis votre dernière évaluation ? '),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cognition_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='COGNITION - Avez-vous des problèmes de mémoire ou d’orientation (comme ne pas savoir où l’on est ou quel jour on est ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cognition_2',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='COGNITION - Si oui, avez-vous constaté une aggravation de ces problèmes au cours des 6 derniers mois ou depuis la dernière évaluation ? '),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cognition_3',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='COGNITION - Si oui, Quelle est la date complète d’aujourd’hui ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='mobilite_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='MOBILITE - Demander au sujet de se lever d’une chaise 5 fois de suite, le plus vite possible, les bras croisés sur la poitrine. Le sujet a-t-il réalisé les 5 levers de chaise ? '),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nutrition_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='NUTRITION - Avez-vous perdu involontairement plus de 3kg au cours de 3 derniers mois ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nutrition_2',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='NUTRITION - Avez-vous perdu de l’appétit récemment ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='santePsychique_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='SANTE PSYCHIQUE - Au cours des deux dernières semaines, vous êtes-vous senti déprimé ou sans espoir ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='santePsychique_2',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name="SANTE PSYCHIQUE - Au cours des deux dernières semaines, avez-vous trouvé peu d'intérêt ou de plaisir à faire les choses ?"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='vision_1',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='VISION - Avez-vous des problèmes de vue : difficultés pour voir de loin ou pour lire (avec vos lunettes si vous en portez). Avez-vous des maladies de l’œil\xa0? Avez-vous un traitement pour une hypertension artérielle ou un diabète ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='vision_2',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='VISION - Si oui, Avez-vous consulté un ophtalmologue durant les 12 derniers mois ?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='vision_3',
            field=models.IntegerField(choices=[(1, 'OUI'), (0, 'NON')], null=True, verbose_name='VISION - Si oui, Avez-vous l’impression que votre vue a baissé, avec ou sans vos lunettes, au cours des 6 derniers mois ou depuis votre dernière évaluation ?'),
        ),
    ]
